=== apache/logging-log4j1/src/java/org/apache/log4j/xml/log4j.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Authors: Chris Taylor, Ceki Gulcu. -->

<!-- A configuration element consists of optional renderer
elements,appender elements, categories and an optional root
element. -->

<!ELEMENT configuration (renderer*, appender*,category*,root?)>

<!-- The disableOverride attribute allows the user to override any
     BasicConfigurator.disable invocations made from within the
     application.
     
     By default, disableOverride is "null", meaning that we
     do not touch the disable flag.
     
     Setting the configDebug attribute enables the printing of 
     internal log4j statements from within configurators.

     By default, configDebug is "null", meaning that we not touch the
     configDebug variable.     
-->
     
<!ATTLIST configuration
  disableOverride          (true|false|null)  "null"
  configDebug              (true|false|null)  "null"
>

<!-- renderer elements allow the user to customize the conversion of
message objects to String. -->

<!ELEMENT renderer EMPTY>
<!ATTLIST renderer
  renderedClass  CDATA #REQUIRED
  renderingClass CDATA #REQUIRED
>

<!-- Appenders must have a name and a class. -->
<!-- Appenders may contain an error handler, a layout, optional parameters -->
<!-- and filters. -->
<!ELEMENT appender (errorHandler?, param*, layout?, filter*, appender-ref*)>
<!ATTLIST appender
  name 		ID 	#REQUIRED
  class 	CDATA	#REQUIRED
>

<!ELEMENT layout (param*)>
<!ATTLIST layout
  class		CDATA	#REQUIRED
>



<!ELEMENT filter (param*)>
<!ATTLIST filter
  class		CDATA	#REQUIRED
>


<!-- ErrorHandlers can be of any class. They can admit any number of
parameters. -->

<!ELEMENT errorHandler (param*)> 
<!ATTLIST errorHandler
   class        CDATA   #REQUIRED 
>



<!ELEMENT param EMPTY>
<!ATTLIST param
  name		CDATA   #REQUIRED
  value		CDATA	#REQUIRED
>

<!-- The priority class is org.apache.log4j.Priority by default -->
<!ELEMENT priority (param*)>
<!ATTLIST priority
  class   CDATA	#IMPLIED
  value	  CDATA #REQUIRED
>

<!-- If no priority element is specified, then the configurator MUST not -->
<!-- touch the priority of the named category. -->
<!ELEMENT category (param*, priority?, appender-ref*)>
<!ATTLIST category
  class         CDATA   #IMPLIED
  name		CDATA	#REQUIRED
  additivity	(true|false) "true"  
>

<!ELEMENT appender-ref EMPTY>
<!ATTLIST appender-ref
  ref IDREF #REQUIRED
>

<!-- If no priority element is specified, then the configurator MUST not -->
<!-- touch the priority of root. -->
<!-- The root category always exists and cannot be subclassed. -->
<!ELEMENT root (param*, priority?, appender-ref*)>



<!-- ==================================================================== -->
<!--                       A logging event                                -->
<!-- ==================================================================== -->
<!ELEMENT log4j:eventSet (log4j:event*)>
<!ATTLIST log4j:eventSet
  includesLocationInfo   (true|false) "true"
>



<!ELEMENT log4j:event (log4j:message, log4j:NDC?, log4j:throwable?, 
                       log4j:locationInfo?) >

<!-- The timestamp format is application dependent. -->
<!ATTLIST log4j:event
    category   CDATA #REQUIRED
    priority   CDATA #REQUIRED
    thread     CDATA #REQUIRED
    timestamp  CDATA #REQUIRED
>

<!ELEMENT log4j:message (#PCDATA)>
<!ELEMENT log4j:NDC (#PCDATA)>

<!ELEMENT log4j:throwable (#PCDATA)>

<!ELEMENT log4j:locationInfo EMPTY>
<!ATTLIST log4j:locationInfo
  class  CDATA	#REQUIRED
  method CDATA	#REQUIRED
  file   CDATA	#REQUIRED
  line   CDATA	#REQUIRED
>

=== apache/logging-log4j1/v1_2-branch/src/java/org/apache/log4j/xml/examples/sample3.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
	<appender name="A1" class="org.apache.log4j.net.SocketAppender">
		<param name="RemoteHost" value="localhost"/>
		<param name="Port" value="5000"/>
		<param name="LocationInfo" value="true"/>
		<layout class="org.apache.log4j.PatternLayout">
  		   <param name="ConversionPattern" 
                          value="%t %-5p %c{2} - %m%n"/>
		</layout>
	</appender>
	<appender name="STDOUT" class="org.apache.log4j.ConsoleAppender">
		<layout class="org.apache.log4j.PatternLayout">
  		     <param name="ConversionPattern" 
                            value="%d %-5p [%t] %C{2} (%F:%L) - %m%n"/>
		</layout>
	</appender>
	<category name="org.apache.log4j.xml">
		<priority value="debug"/>
		<appender-ref ref="A1"/>
	</category>
	<root>
		<priority value="debug"/>
		<appender-ref ref="STDOUT"/>
	</root>
</log4j:configuration>

=== apache/logging-log4j1/src/main/javadoc/org/apache/log4j/xml/examples/sample1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

	<appender name="STDOUT" class="org.apache.log4j.ConsoleAppender">
           <layout class="org.apache.log4j.PatternLayout">
             <param name="ConversionPattern"
		    value="%d %-5p [%t] %C{2} (%F:%L) - %m%n"/>
           </layout>	    
	</appender>
	
	<category name="org.apache.log4j.xml">
	  <priority value="info" />
	</category>
	
	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="STDOUT" />
	</root>
	
</log4j:configuration>

=== apache/logging-log4j1/src/main/javadoc/org/apache/log4j/xml/examples/sample4.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/"
                     configDebug="true">

	<appender name="ASYNC" class="org.apache.log4j.AsyncAppender">
	        <appender-ref ref="TEMP"/>
	</appender>

	<appender name="TEMP" class="org.apache.log4j.FileAppender">
		<param name="File" value="temp"/>
		<layout class="org.apache.log4j.PatternLayout">
  		     <param name="ConversionPattern" 
                            value="%d %-5p [%t] %C{2} (%F:%L) - %m%n"/>
		</layout>
	</appender>

	<root>
		<priority value="debug"/>
		<appender-ref ref="ASYNC"/>
	</root>
</log4j:configuration>

=== apache/logging-log4j1/src/performance/java/org/apache/log4j/performance/xml/logging2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<!-- PropertyConfigurator equivalent:
log4j.rootCategory=, NULL
log4j.category.A0123456789=INFO
log4j.appender.NULL=org.apache.log4j.performance.NullAppender
log4j.appender.NULL.layout=org.apache.log4j.PatternLayout
log4j.appender.NULL.layout.ConversionPattern=%p - %m%n
-->
<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

        <appender name="NULL" class="org.apache.log4j.performance.NullAppender">
           <layout class="org.apache.log4j.PatternLayout">
              <param name="ConversionPattern" value="%p - %m%n"/>
	   </layout>
	</appender>
 
        <category name="A0123456789">  	
	   <priority value ="info" />
        </category>  	

	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="NULL" />
	</root>
	
</log4j:configuration>

=== apache/logging-log4j1/tests/input/xml/customLevel1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

  <appender name="TEMP" class="org.apache.log4j.FileAppender">
    <param name="Append" value="false" />
    <param name="File"   value="output/temp" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern"
	value="%-5p %c{2} - %m\n"/>
    </layout>
  </appender>

  <root>
    <level value="TRACE" class="org.apache.log4j.xml.XLevel"/>
    <appender-ref ref="TEMP" />
  </root>
</log4j:configuration>

=== apache/logging-log4j1/src/performance/java/org/apache/log4j/performance/xml/logging106.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>
        <appender name="NULL" class="org.apache.log4j.FileAppender">
           <param name="File" value="temp"/>
           <param name="Append" value="false"/>

           <layout class="org.apache.log4j.PatternLayout">
              <param name="ConversionPattern" 
                     value="%d{yyyy-MM-dd HH:mm:ss,SSS} [%t] %-5p %c %x - %m%n"/>
	   </layout>
	</appender>
 
        <category name="A0123456789">  	
	   <priority value ="info" />
        </category>  	

	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="NULL" />
	</root>
	
</log4j:configuration>

=== apache/logging-log4j1/src/main/java/org/apache/log4j/xml/examples/extension2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd" [
  <!ENTITY XCategory "org.log4j.xml.examples.XCategory">
]>


<!-- A sample file demonstrating the configuration of Category and
     Priority sub-classes.  -->



<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
	<appender name="STDOUT" class="org.apache.log4j.ConsoleAppender">
           <layout class="org.apache.log4j.PatternLayout">
             <param name="ConversionPattern"
		    value="%d %-5p [%t] %c %C{3} (%F:%L) - %m\n"/>
           </layout>	    
	</appender>
	
	<category name="some.cat"
                  class="org.apache.log4j.xml.examples.XCategory">
	  <priority value="TRACE"
                   class="org.apache.log4j.xml.examples.XPriority"/>
          <param name="Suffix" 
                 value=" (Freedom as in the capacity to exercise choice.)"/>
	</category>
	
	<root>
	   <priority value ="trace" 
                     class="org.apache.log4j.xml.examples.XPriority"/>
   	   <appender-ref ref="STDOUT" />
	</root>
	
</log4j:configuration>

=== apache/logging-log4j1/src/java/org/apache/log4j/xml/examples/sample2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "log4j.dtd">

<configuration>

	<appender name="A1" class="org.apache.log4j.FileAppender">
            <param name="File"   value="A1.log" />
            <param name="Append" value="false" />	    	
            <layout class="org.apache.log4j.PatternLayout">
		<param name="ConversionPattern" value="%t %-5p %c{2} - %m\n"/>
            </layout>	    
	</appender>
	
	<appender name="STDOUT" class="org.apache.log4j.FileAppender">
		<param name="File" value="System.out" />
		
		<layout class="org.apache.log4j.PatternLayout">
                   <param name="ConversionPattern"
		          value="%d %-5p [%t] %C{2} (%F:%L) - %m\n"/>
		</layout>		
	</appender>
	
	<category name="org.apache.log4j.xml">
	  <priority value="debug" />
  	  <appender-ref ref="A1" />
	</category>
	
	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="STDOUT" />
	</root>
	
</configuration>
