=== apache/logging-log4j1/src/java/org/apache/log4j/xml/log4j.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Authors: Chris Taylor, Ceki Gulcu. -->

<!-- A configuration element consists of optional renderer
elements,appender elements, categories and an optional root
element. -->

<!ELEMENT configuration (renderer*, appender*,category*,root?)>

<!-- The disableOverride attribute allows the user to override any
     BasicConfigurator.disable invocations made from within the
     application.
     
     By default, disableOverride is "null", meaning that we
     do not touch the disable flag.
     
     Setting the configDebug attribute enables the printing of 
     internal log4j statements from within configurators.

     By default, configDebug is "null", meaning that we not touch the
     configDebug variable.     
-->
     
<!ATTLIST configuration
  disableOverride          (true|false|null)  "null"
  configDebug              (true|false|null)  "null"
>

<!-- renderer elements allow the user to customize the conversion of
message objects to String. -->

<!ELEMENT renderer EMPTY>
<!ATTLIST renderer
  renderedClass  CDATA #REQUIRED
  renderingClass CDATA #REQUIRED
>

<!-- Appenders must have a name and a class. -->
<!-- Appenders may contain an error handler, a layout, optional parameters -->
<!-- and filters. -->
<!ELEMENT appender (errorHandler?, param*, layout?, filter*, appender-ref*)>
<!ATTLIST appender
  name 		ID 	#REQUIRED
  class 	CDATA	#REQUIRED
>

<!ELEMENT layout (param*)>
<!ATTLIST layout
  class		CDATA	#REQUIRED
>



<!ELEMENT filter (param*)>
<!ATTLIST filter
  class		CDATA	#REQUIRED
>


<!-- ErrorHandlers can be of any class. They can admit any number of
parameters. -->

<!ELEMENT errorHandler (param*)> 
<!ATTLIST errorHandler
   class        CDATA   #REQUIRED 
>



<!ELEMENT param EMPTY>
<!ATTLIST param
  name		CDATA   #REQUIRED
  value		CDATA	#REQUIRED
>

<!-- The priority class is org.apache.log4j.Priority by default -->
<!ELEMENT priority (param*)>
<!ATTLIST priority
  class   CDATA	#IMPLIED
  value	  CDATA #REQUIRED
>

<!-- If no priority element is specified, then the configurator MUST not -->
<!-- touch the priority of the named category. -->
<!ELEMENT category (param*, priority?, appender-ref*)>
<!ATTLIST category
  class         CDATA   #IMPLIED
  name		CDATA	#REQUIRED
  additivity	(true|false) "true"  
>

<!ELEMENT appender-ref EMPTY>
<!ATTLIST appender-ref
  ref IDREF #REQUIRED
>

<!-- If no priority element is specified, then the configurator MUST not -->
<!-- touch the priority of root. -->
<!-- The root category always exists and cannot be subclassed. -->
<!ELEMENT root (param*, priority?, appender-ref*)>



<!-- ==================================================================== -->
<!--                       A logging event                                -->
<!-- ==================================================================== -->
<!ELEMENT log4j:eventSet (log4j:event*)>
<!ATTLIST log4j:eventSet
  includesLocationInfo   (true|false) "true"
>



<!ELEMENT log4j:event (log4j:message, log4j:NDC?, log4j:throwable?, 
                       log4j:locationInfo?) >

<!-- The timestamp format is application dependent. -->
<!ATTLIST log4j:event
    category   CDATA #REQUIRED
    priority   CDATA #REQUIRED
    thread     CDATA #REQUIRED
    timestamp  CDATA #REQUIRED
>

<!ELEMENT log4j:message (#PCDATA)>
<!ELEMENT log4j:NDC (#PCDATA)>

<!ELEMENT log4j:throwable (#PCDATA)>

<!ELEMENT log4j:locationInfo EMPTY>
<!ATTLIST log4j:locationInfo
  class  CDATA	#REQUIRED
  method CDATA	#REQUIRED
  file   CDATA	#REQUIRED
  line   CDATA	#REQUIRED
>

=== apache/logging-log4j1/src/java/org/apache/log4j/xml/examples/sample4.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE configuration SYSTEM "log4j.dtd">

<configuration configDebug="true">

	<appender name="ASYNC" class="org.log4j.AsyncAppender">
	        <appender-ref ref="TEMP"/>
	</appender>

	<appender name="TEMP" class="org.log4j.FileAppender">
		<param name="File" value="temp"/>
		<layout class="org.log4j.PatternLayout">
  		     <param name="ConversionPattern" 
                            value="%d %-5p [%t] %C{2} (%F:%L) - %m\n"/>
		</layout>
	</appender>

	<root>
		<priority value="debug"/>
		<appender-ref ref="ASYNC"/>
	</root>
</configuration>

=== apache/logging-log4j1/src/java/org/apache/log4j/performance/xml/logging224.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>
  <appender name="NULL" class="org.apache.log4j.FileAppender">
    <param name="File" value="temp"/>
    <param name="Append" value="false"/>
    <param name="ImmediateFlush" value="false"/>
    <param name="BufferedIO" value="true"/>
    <layout class="org.apache.log4j.TTCCLayout">
      <param name="DateFormat" 
	value="ISO8601"/>
    </layout>
  </appender>
  
  <category name="A0123456789">  	
    <priority value ="info" />
  </category>  	
  
  <root>
    <priority value ="debug" />
    <appender-ref ref="NULL" />
  </root>
  
</log4j:configuration>

=== apache/logging-log4j1/src/java/org/apache/log4j/test/xml/ext1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'
                     configDebug="true">

	<appender name="TEMP" class="org.apache.log4j.FileAppender">
                <param name="Append" value="false" />
		<param name="File"   value="current.reg" />
		<layout class="org.apache.log4j.PatternLayout">
 		    <param name="ConversionPattern"
		           value="%-5p %c{2} - %m\n"/>
		</layout>

		<filter class="org.apache.log4j.varia.PriorityMatchFilter">
                  <param name="PriorityToMatch" value="TRACE#org.apache.log4j.xml.examples.XPriority" />
                  <param name="AcceptOnMatch" value="true" />
		</filter>


	</appender>
 
	<root>
          <appender-ref ref="TEMP" />	
          <priority value ="TRACE" class="org.apache.log4j.xml.examples.XPriority"/>       
	</root>
</log4j:configuration>

=== apache/logging-log4j1/src/performance/java/org/apache/log4j/performance/xml/logging300.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

-->

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>
        <appender name="ASYNC" class="org.apache.log4j.AsyncAppender">
   	   <appender-ref ref="TEMP" />
	</appender>

        <appender name="TEMP" class="org.apache.log4j.FileAppender">
           <param name="File" value="test"/>
           <param name="Append" value="false"/>
           <param name="ImmediateFlush" value="false"/>
           <layout class="org.apache.log4j.SimpleLayout">
	   </layout>
	</appender>
 
        <category name="A0123456789">  	
	   <priority value ="info" />
        </category>  	

	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="ASYNC" />
	</root>
	
</log4j:configuration>

=== apache/logging-log4j1/src/performance/java/org/apache/log4j/performance/xml/logging103.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>
        <appender name="TEMP" class="org.apache.log4j.FileAppender">
           <param name="File" value="temp"/>
           <param name="Append" value="false"/>

           <layout class="org.apache.log4j.PatternLayout">
              <param name="ConversionPattern" 
                     value="%r [%t] %-5p %c - %m%n"/>
	   </layout>
	</appender>
 
        <category name="A0123456789">  	
	   <priority value ="info" />
        </category>  	

	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="TEMP" />
	</root>
	
</log4j:configuration>

=== apache/logging-log4j1/tests/input/xml/customLevel3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'
                     debug="false">

  <appender name="TEMP" class="org.apache.log4j.FileAppender">
    <param name="Append" value="false" />
    <param name="File"   value="output/temp" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern"
	value="%-5p %c{2} - %m\n"/>
    </layout>
    
    <filter class="org.apache.log4j.varia.LevelMatchFilter">
      <param name="LevelToMatch" value="TRACE#org.apache.log4j.xml.XLevel" />
      <param name="AcceptOnMatch" value="true" />
    </filter>
    
    <filter class="org.apache.log4j.varia.DenyAllFilter"/>

  </appender>

  <root>
    <level value="TRACE" class="org.apache.log4j.xml.XLevel"/>
    <appender-ref ref="TEMP" />
  </root>

</log4j:configuration>

=== apache/logging-log4j1/src/java/org/apache/log4j/performance/xml/logging105.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "log4j.dtd">

<configuration>
        <appender name="NULL" class="org.log4j.FileAppender">
           <param name="File" value="temp"/>
           <param name="Append" value="false"/>

           <layout class="org.log4j.PatternLayout">
              <param name="ConversionPattern" 
                     value="%d{ISO8601} [%t] %-5p %c %x - %m%n"/>
	   </layout>
	</appender>
 
        <category name="A0123456789">  	
	   <priority value ="info" />
        </category>  	

	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="NULL" />
	</root>
	
</configuration>

=== apache/logging-log4j1/src/java/org/apache/log4j/performance/xml/logging9.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "log4j.dtd">

<!-- PropertyConfigurator equivalent:
log4j.rootCategory=, NULL
log4j.category.A0123456789=INFO
log4j.appender.NULL=org.apache.log4j.performance.NullAppender
log4j.appender.NULL.layout=org.apache.log4j.TTCCLayout
log4j.appender.NULL.layout.DateFormat=RELATIVE
-->
<configuration>

        <appender name="NULL" class="org.apache.log4j.performance.NullAppender">
           <layout class="org.apache.log4j.TTCCLayout">
              <param name="DateFormat" value="ISO8601"/>
	   </layout>
	</appender>
 
        <category name="A0123456789">  	
	   <priority value ="info" />
        </category>  	

	<root>
	   <priority value ="debug" />
   	   <appender-ref ref="NULL" />
	</root>
	
</configuration>
